---
name: 🔖 Container Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  container-release:
    name: Container Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Update README with release SHA
        run: |
          # Update the SHA badge in README (expects a placeholder comment)
          sed -i "s|<!--sha-badge-->.*<!--/sha-badge-->|<!--sha-badge-->![SHA](https://img.shields.io/badge/release%20sha-${GITHUB_SHA}-blue)<!--/sha-badge-->|g" README.md
          
      - name: Commit updated README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "chore: update release SHA to ${GITHUB_SHA}"
          git push